### ISSUE TITLE
SDK returning Error: bad response

### ISSUE THREAD

**Issue by tster** [X2Y2-io/x2y2-sdk#5]
**Describe the bug** 
When following the instructions to make an offer as described at https://github.com/X2Y2-io/x2y2-sdk#making-offers--collection-offers, an `Error: bad response` is thrown.

**Code sample**
```JavaScript
const offerResponse = await offer({
        network,
        signer: WALLET, // Signer of the buyer
        isCollection: false, // bool, set true for collection offer
        tokenAddress: '0xBC4CA0EdA7647A8aB7C2061c2E118A18a936f13D', // string, contract address of NFT collection
        tokenId: '2491', // string, token ID of the NFT, use empty string for collection offer
        currency: '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', // string, contract address of WETH, '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2'
        price: '10', // string, eg. '1000000000000000000' for 1 WETH
        expirationTime: 1657273865, // number, the unix timestamp when the listing will expire, in seconds
      })
    } catch (error) {
        console.log(error)
    }
```

**Expected behavior**
The API should return a 200 status code. If something is wrong with the order, one of the [custom error codes](https://github.com/X2Y2-io/x2y2-sdk#error-codes-of-api-response) should be thrown.

**Comment by Tster** [comment]
I've managed to diagnose this error. The issue was having not having enough WETH for the offer in the wallet.

I think the error handling for this case should be improved, with the creation of a dedicated `insufficient funds` error code.
