### ISSUE TITLE
Missing error codes 1002 and 2014

### ISSUE THREAD

**Issue by tster** [X2Y2-io/x2y2-sdk#9]
[Two Discord users](https://discord.com/channels/977147775366082560/977147775366082564/995164528989970552) reported running into error codes 1002 and 2014. Information about these errors is missing from the SDK docs.

**Comment by shermiexyz** [comment]
Information about these errors have been added to SDK docs. 
https://github.com/X2Y2-io/x2y2-sdk#error-codes-of-api-response

**Comment by tster** [comment]
Resolved above
